version: '3'
services:
  halyard:
    build: .
    volumes:
      - ~/.hal:/home/spinnaker/.hal
    environment:
      SPINNAKER_VERSION: $SPINNAKER_VERSION
      SPINNAKER_GKE_CLUSTER_NAME: $SPINNAKER_GKE_CLUSTER_NAME
      SPINNAKER_GKE_CLUSTER_ZONE: $SPINNAKER_GKE_CLUSTER_ZONE
      SPINNAKER_GKE_CLUSTER_PROJECT: $SPINNAKER_GKE_CLUSTER_PROJECT
      SPINNAKER_GKE_CLUSTER_READ_ROLES: $SPINNAKER_GKE_CLUSTER_READ_ROLES
      SPINNAKER_GKE_CLUSTER_WRITE_ROLES: $SPINNAKER_GKE_CLUSTER_WRITE_ROLES
      SPINNAKER_STORAGE_BUCKET_NAME: $SPINNAKER_STORAGE_BUCKET_NAME
      SPINNAKER_STORAGE_BUCKET_LOCATION: $SPINNAKER_STORAGE_BUCKET_LOCATION
      GKE_CLUSTER_NAMES: $GKE_CLUSTER_NAMES
      GKE_CLUSTER_ZONES: $GKE_CLUSTER_ZONES
      GKE_CLUSTER_PROJECTS: $GKE_CLUSTER_PROJECTS
      GKE_CLUSTER_READ_ROLES: $GKE_CLUSTER_READ_ROLES
      GKE_CLUSTER_WRITE_ROLES: $GKE_CLUSTER_WRITE_ROLES
      CLOUDBUILD_PROJECT: $CLOUDBUILD_PROJECT
      ADMIN: $ADMIN
      OAUTH2_CLIENT_ID: $OAUTH2_CLIENT_ID
      OAUTH2_CLIENT_SECRET: $OAUTH2_CLIENT_SECRET
      GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
      SLACK_TOKEN: $SLACK_TOKEN
      SLACK_BOT_NAME: $SLACK_BOT_NAME
      DOCKER_REGISTRY_ADDRESS: $DOCKER_REGISTRY_ADDRESS
      DOMAIN: $DOMAIN

